dd3tech/bui

.codesandbox/ci.json
.github/workflows/chromatic.yml

This PR can be related with:
- change to active chromatic publish when on push
- add sandboxes to codesandbox ci

ci: chromatic and codesandbox 

---

exports.json

- Exports of some components was added to improve the three-shaking
- exports.json

feat: add missing exports of components

---

src/components/Form/Input/BaseInput.tsx
src/components/Form/Input/CurrencyInput.test.tsx
src/components/Form/Select.tsx
src/components/Form/TextArea.test.tsx
src/components/Form/TextArea.tsx
src/components/Form/shared.ts
src/stories/Input.stories.tsx
src/stories/TextArea.stories.tsx

- src/components/Form/Input/CurrencyInput.test.tsx
- src/components/Form/TextArea.test.tsx
- src/components/Form/TextArea.tsx
- src/components/Form/shared.ts
- src/stories/Input.stories.tsx
- src/stories/TextArea.stories.tsx

fix: animation is added to the select, inputs and textarea

---

src/components/Form/Select.test.tsx
src/components/Form/Select.tsx
src/components/Form/shared.ts

- src/components/Form/Select.test.tsx

fix: dropdown was not overlapping certain items

---

src/components/Tabs/TabGroup.tsx

Add validation was added for the scroll of the tabs
Not yet
- Mannualy

Fix(TabGroup): Add validation was added for the scroll of the tabs

---

src/components/Form/Select.tsx

Change the update state on useEffect to improve reactivity when value is changed async
- `Select.tsx`

fix: switched to useEffect to improve reactivity when set state

---

src/components/Tabs/TabGroup.tsx

fix scroll tabgroup
- Not
- Mannualy

fix(Tabgroup): fix scroll tabgroup

---

src/components/Form/Input/DateInput.tsx
src/components/Form/TextArea.tsx
src/stories/CircleButtons.stories.tsx
src/stories/Input.stories.tsx

- src/components/Form/Input/DateInput.tsx
- src/stories/Input.stories.tsx
all tests passed ✅

fix: the default variant of DateInput is changed

---

src/components/Form/Input/CurrencyInput.test.tsx
src/components/Form/Input/CurrencyInput.tsx

- src/components/Form/Input/CurrencyInput.test.tsx
all tests passed ✅

fix: $ is added inside the currency input value

---

src/components/Form/Select.tsx

The dropdown menu would not drop down when clicking on the chevron icons
all tests passed ✅

fix: pull down the dropdown menu by clicking the chevron icons

---

src/components/Form/Input/CurrencyInput.test.tsx
src/components/Form/Input/CurrencyInput.tsx
src/stories/Input.stories.tsx

- src/components/Form/Input/CurrencyInput.test.tsx
- src/stories/Input.stories.tsx
all test passed ✅

feat: an (optional) prefix can be added to the inputCurrency variant

---

src/components/Form/Select.tsx
src/components/Form/shared.ts

This pr includes:
- remove classes to prevent the bug
- refactor shared to use composeClasses
Closes #76 
- Mannualy with storybook 

fix(Select): remove incorrect bg and text color on endAdornment 

---

src/hooks/useTooltip.ts

- src/hooks/useTooltip.ts
all test passed ✅

feat: click event handler is added

---

src/hooks/useTooltip.ts

An array of modifiers can be received in the useTooltip
[CD-1029](https://dd360.atlassian.net/browse/CD-1029)
- src/hooks/useTooltip.ts
all test passed ✅

feat: an array of modifiers can be received in the useTooltip

---

exports.json
src/components/RangeSlider/MultiRangeSlider.tsx
src/components/index.ts

fix: typo on export declaration of the ranger component

---

src/components/SideBar/SideBar.tsx
src/stories/SideBar.stories.tsx

Props are added to be able to show loading skeletons when the data has not yet loaded
[CD-1109](https://dd360.atlassian.net/browse/CD-1109)
All test passed

feat: skeleton is added to the sidebar

---

src/components/SideBar/SideBar.test.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBarBadge.tsx
src/components/SideBar/SideBarHeader.tsx
src/components/SideBar/SideBarItem.tsx
src/components/SideBar/SkeletonSideBarList.tsx
src/stories/SideBar.stories.tsx

"A renewed SideBar is implemented with a clean and minimalist design to enhance navigation and user experience. The new SideBar provides clear and structured navigation."
[CD-1049](https://dd360.atlassian.net/browse/CD-1049)
- src/components/SideBar/SideBar.test.tsx
- src/components/SideBar/SideBarBadge.tsx
- src/components/SideBar/SideBarHeader.tsx
- src/components/SideBar/SkeletonSideBarList.tsx

feat: SideBar component is refactored

---

src/components/SideBar/SideBarHeader.tsx
src/components/SideBar/SideBarItem.tsx
src/stories/SideBar.stories.tsx

Add maximum length to sidebar items
[CD-1049](https://dd360.atlassian.net/browse/CD-1049)
- src/components/SideBar/SideBarHeader.tsx
All test passed

fix: add maximum length to sidebar items

---

src/components/SideBar/SideBar.test.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBarItem.tsx
src/stories/SideBar.stories.tsx
tailwind.config.js

The sidebar should not overlap the content of the page
[CD-1049](https://dd360.atlassian.net/browse/CD-1049)
- src/components/SideBar/SideBar.test.tsx

fix: the sidebar should not overlap the content of the page

---

src/components/Form/Input/DateInput.tsx

Change validation value
Not
- src/components/Form/Input/DateInput.tsx
- Mannualy 

fix: change validation value

---

src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBarItem.tsx

Bug caused when using StrictMode is corrected

fix: bug caused when using StrictMode is corrected

---

src/components/SideBar/SideBarItem.tsx

The animation speed of the display of the subitems is changed

fix: the animation speed of the display of the subitems is changed

---

src/components/SideBar/SideBarItem.tsx

This comment is added to be able to perform the release

feat: for mobile devices, the sidebar will overlay the content

---

src/components/Form/InputCurrency.tsx

Add the possibility to use onKeyPress event
- https://dd360.atlassian.net/browse/CD-1328
- src/components/Form/InputCurrency.tsx
- Manually

Feat(InputCurrency): add key press event on input currency

---

src/components/Form/Input/CurrencyInput.tsx

null
src/components/Form/Input/CurrencyInput.tsx
All tests passed

fix: Adding decimalScale prop to Input type=currency

---

src/components/SideBar/SkeletonSideBarList.tsx

A change was made in the height of the sidebarlist skeleton
- Not
- src/components/SideBar/SkeletonSideBarList.tsx
- Mannualy 

Fix(Sidebar): Change height skeleton sidebarlist

---

exports.json
package.json

Export transition component correctly
none
- exports.json
- package.json
- Manually

fix: transition component exports

---

src/components/Form/Input/CurrencyInput.tsx
src/stories/Input.stories.tsx

- Fixed bug in value formatting when 0 is entered
- Maximum and minimum limit is added
[CD-1553](https://dd360.atlassian.net/browse/CD-1553)
- src/stories/Input.stories.tsx

fix(CurrencyInput): fixed bug in value formatting when 0 is entered

---

src/components/SideBar/SideBarBadge.tsx
src/components/SideBar/SideBarItem.tsx
src/stories/SideBar.stories.tsx

* https://dd360.atlassian.net/jira/software/c/projects/CD/boards/12?modal=detail&selectedIssue=CD-1357&assignee=6397d19e7145571a7ea7e0de
* src/components/SideBar/SideBarBadge.tsx
* src/components/SideBar/SideBarItem.tsx
* src/stories/SideBar.stories.tsx

Feat(notifications in side bar) props are added to the sidebar item to be able to personalize the badge

---

exports.json
package.json

Export Image component
none
- package.json
- exports.json
- Manually

Fix(Image): export Image component

---

src/components/Buttons/ShapeButton.tsx
src/components/Form/Input/Input.tsx
src/components/Form/Input/MonthInput.tsx
src/components/Form/shared.ts
src/stories/Input.stories.tsx

fix: add missing props on DatePicker and ShapeButton components

---

src/components/Tabs/TabGroup.tsx

Add onChange dependency to onClick function
- none
- Manually

Fix(TabGroup): add onchange dependency

---

src/components/Tabs/Tab.tsx

Added the possibility for the tab to be hidden
not
- Mannualy 

fix(Tab): add prop hidden

---

src/components/SideBar/SideBar.test.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBarItem.tsx
src/stories/SideBar.stories.tsx

Summary
Added the possibility of rendering children in the sub-sub items
Task
not
Affected sections
How did you test this change?
- Mannualy with storybook 🎨

feat(sidebar): added the possibility of rendering sub-sub items

---

src/components/SideBar/SideBarItem.tsx

fix(sidebar): revert to toggle menu

---

src/components/SideBar/SideBarItem.tsx

Padding was modified in subitems
not
- Mannualy 

Fix(Sidebar): Padding was modified in subitems

---

src/components/AutoComplete/AutoComplete.tsx

The select type was added in autocomplete
not
- src/components/AutoComplete/AutoComplete.tsx
- Mannualy 

Fix(Autocomplete): The select type was added in autocomplete

---

src/components/FileViewer/FileViewer.tsx

Validation was added in case the url is an empty string
not
- src/components/FileViewer/FileViewer.tsx
- Mannualy 

Fix(FileViewer): Validation was added to the url

---

src/components/AutoComplete/AutoComplete.tsx

The value update was added and styles were modified in the list
not
- src/components/AutoComplete/AutoComplete.tsx
- Mannualy 

Fix(Autocomplete) : The value update was added

---

src/components/Tabs/Tab.tsx

Fix (Tab): Change style tab

---

src/components/Modal/Modal.tsx

Add validation stop propagation
not

Fix(Modal): Add validation stop propagation

---

src/components/Form/Input/InputFile.tsx
src/components/Typography/Text.test.tsx
src/components/Typography/Text.tsx
src/stories/InputFile.stories.tsx

- Add default value on the text component
- Fix disable prop on file input
- https://dd360.atlassian.net/browse/CD-2247
- src/components/Typography/Text.test.tsx
- src/components/Typography/Text.tsx
- src/stories/InputFile.stories.tsx
- Manually

Feat(Text): text default value and input file

---

src/components/Tooltip/Tooltip.tsx

add z-index
The z index was added
not
- src/components/Tooltip/Tooltip.tsx

Fix(Tooltip): The z index was added

---

src/components/Tabs/Tab.tsx
src/components/Tabs/TabGroup.tsx
src/components/Tabs/Tabs.test.tsx
src/stories/Tabs.stories.tsx

Add new variant in the component tab called tertiary
[OK-100](https://dd360.atlassian.net/browse/OK-100)
- src/components/Tabs/Tabs.test.tsx
- src/stories/Tabs.stories.tsx
Mannualy with storybook 🎨
Added test to tab component :robot: 

Fix: update component tabs

---

src/components/Pagination/Pagination.tsx

Remove useEffect
not
- src/components/Pagination/Pagination.tsx
- Mannualy with storybook 🎨

Fix(Pagination): Remove useEffect

---

src/components/DatePicker/DatePicker.tsx

Change validation day active
Issue: https://github.com/dd3tech/bui/issues/187
- src/components/DatePicker/DatePicker.tsx
- Mannualy

Fix(DatePicker): Change validation day active

---

src/components/AutoComplete/AutoComplete.test.tsx
src/components/AutoComplete/AutoComplete.tsx
src/stories/AutoComplete.stories.tsx

Add the possibility of disabling options
- https://dd360.atlassian.net/browse/CD-2453
- src/components/AutoComplete/AutoComplete.test.tsx
- src/components/AutoComplete/AutoComplete.tsx
- src/stories/AutoComplete.stories.tsx
- src/components/AutoComplete/AutoComplete.test.tsx

Feat(Autocomplete): disable autocomplete options

---

src/components/SideBar/SideBarItem.tsx

Change position top tooltip sibebar
- not 
- Mannualy

Fix(Sidebar): Change position top tooltip sibebar

---

src/components/Form/Input/InputFile.tsx

Changed dependency in function where error message is returned
not

Fix(InputFile): Changed dependency in function where error message is returned

---

src/components/Typography/Text.tsx

Moved const out of the switch
not
- src/components/Typography/Text.tsx

Fix(Text): Moved const out of the switch

---

src/components/DatePicker/DatePicker.tsx
src/components/Form/Input/MonthInput.tsx

The prop value was added and the date formatting was done
not

Fix(MonthInput): The prop value was added and the date formatting was done

---

src/components/Switch/Switch.tsx

Add prop size
- not
- src/components/Switch/Switch.tsx

Fix(Switch): Add prop size

---

src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBarItem.tsx
src/stories/SideBar.stories.tsx

Added possibility of notifications in sidebar subitems
- https://dd360.atlassian.net/jira/software/c/projects/CD/boards/12?assignee=6397d027fbf54baf29036449&selectedIssue=CD-2705

Fix(Sidebar): Added possibility of notifications in sidebar subitems

---

exports.json
package.json

Import layout components correctly
none
- exports.json
- package.json
- Manually

refactor: export layout components correctly

---

src/components/SideBar/SideBar.test.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SidebarDropdown.tsx
src/components/SideBar/ToggleSideBar.tsx

Improve the layout on sidebar
- https://dd360.atlassian.net/browse/PD-469
- src/components/SideBar/SideBar.test.tsx
- src/components/SideBar/SidebarDropdown.tsx
- src/components/SideBar/ToggleSideBar.tsx
- src/components/SideBar/SideBar.test.tsx

Fix(Sidebar): sidebar layout issues

---

src/components/FileViewer/FileViewer.tsx
src/components/FileViewer/index.ts
src/components/index.ts

Export file viewer correctly
none
- src/components/FileViewer/index.ts
- Manually

Fix(FileViewer): export file viewer correctly

---

src/components/SideBar/SideBarItem.tsx

Added styles to sidebar icon due to safari problems
- not

Fix(Sidebar): Added styles to sidebar icon due to safari problems

---

src/components/Form/Input/MonthInput.tsx

some corrections were made to the month-year input.
not

Fix(MonthInput): some corrections were made to the month-year input.

---

src/components/SideBar/SideBar.test.tsx

Fix: rollback

---

src/components/Callout/Callout.tsx

add call to action in callout
not
- src/components/Callout/Callout.tsx

Fix(Callout): add call to action in callout

---

src/components/Form/Input/WrapperInput.tsx

Added container for input and message
- src/components/Form/Input/WrapperInput.tsx

Fix(WrapperInput): Added container for input and message

---

src/components/Avatar/Avatar.tsx
src/components/Badge/Badge.tsx
src/components/Buttons/ButtonGroup.tsx
src/components/Card/Card.tsx
src/components/Form/Input/InputFile.tsx
src/components/Form/Input/PercentageInput.tsx
src/components/Form/Input/WrapperInput.tsx
src/components/Image/Image.tsx
src/components/ImageIcon/ImageIcon.tsx
src/components/Kbd/Kbd.tsx
src/components/Layout/Overflow/Overflow.tsx
src/components/Layout/Row/Row.tsx
src/components/Modal/Modal.tsx
src/components/Pagination/Pagination.tsx
src/components/Phase/Phase.tsx
src/components/ProgressBar/ProgressBar.tsx
src/components/ProgressCircle/ProgressCircle.tsx
src/components/Stepper/Stepper.tsx
src/components/Tag/Tag.tsx
src/components/Typography/Text.tsx

defaultProps was removed
- not
- src/components/Avatar/Avatar.tsx
- src/components/Badge/Badge.tsx
- src/components/Buttons/ButtonGroup.tsx
- src/components/Card/Card.tsx
- src/components/Form/Input/PercentageInput.tsx
- src/components/Form/Input/WrapperInput.tsx
- src/components/Image/Image.tsx
- src/components/ImageIcon/ImageIcon.tsx
- src/components/Kbd/Kbd.tsx
- src/components/Layout/Overflow/Overflow.tsx
- src/components/Layout/Row/Row.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Phase/Phase.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/components/ProgressCircle/ProgressCircle.tsx
- src/components/Stepper/Stepper.tsx
- src/components/Tag/Tag.tsx
- src/components/Typography/Text.tsx …

Fix(logs): defaultProps was removed

---

src/components/DatePicker/DatePicker.tsx
src/components/Form/Input/BaseInput.tsx
src/components/Form/Input/DateInput.tsx

add className date picker input date
-not
- src/components/Form/Input/DateInput.tsx

fix: add className date picker input date

---

src/components/Form/Select.tsx

Add select input variant and fix on click icon
none
- Manually

refactor: remove unused var

---

src/components/Form/Select.test.tsx

Add select input test
none
- src/components/Form/Select.test.tsx
- src/components/Form/Select.test.tsx

Fix(Select): add select input test

---

src/components/Form/Select.tsx
src/components/Form/shared.ts

Display the label before the user interacts with the component
none
- src/components/Form/shared.ts
- Manually

Fix(Select): secondary select label

---

src/components/AsideModal/AsideModal.tsx
src/components/ConfirmDialog/ConfirmDialog.tsx
src/components/Filters/FilterDate.tsx
src/components/Filters/FilterRange.tsx
src/components/Filters/FilterRangeSlider.tsx
src/components/Filters/FilterSelect.tsx
src/components/Filters/FilterSelectMulti.tsx

small changes in asideModal and confirmDialog
- not 
- src/components/AsideModal/AsideModal.tsx
- src/components/ConfirmDialog/ConfirmDialog.tsx

Fix: small changes in asideModal and confirmDialog

---

src/components/Tabs/TabGroup.tsx

Update tap indicator
- none
- Manually

Fix(TabGroup): update tab indicator

---

src/components/Form/Select.tsx
src/components/Form/TextArea.tsx

Styles were modified in text area and select components
- not
- src/components/Form/TextArea.tsx

Fix(Select-TextArea): Styles were modified in text area and select components

---

src/components/Phase/Phase.tsx

Change alert icon color
none
- src/components/Phase/Phase.tsx
- Manually

Fix(Phase): change alert icon color

---

src/components/Callout/Callout.tsx

description custom was added as a new prop
- not
- src/components/Callout/Callout.tsx

Fix(Callout): description custom was added as a new prop

---

src/components/AsideModal/AsideModal.tsx

Fix(AsideModal): Add margin top title

---

src/components/Form/Input/YearInput.tsx

- Fix input year value on change
- https://dd360.atlassian.net/browse/PD-985
- src/components/Form/Input/YearInput.tsx
- Manually

Fix(Input): set year on change value

---

src/components/FileViewer/FileViewer.tsx

- Retry load on document load error
- https://dd360.atlassian.net/browse/PD-1086
- src/components/FileViewer/FileViewer.tsx
- Manually

Fix(FileViewer): file viewer retry on error

---

exports.json
src/components/TopPage/TopPage.test.tsx
src/components/TopPage/TopPage.tsx
src/components/TopPage/index.ts
src/stories/TopPage.stories.tsx
src/utils/utils.ts

New TopPage component
- https://dd360.atlassian.net/jira/software/projects/PD/boards/82?assignee=6397d027fbf54baf29036449&selectedIssue=PD-1169
- src/components/TopPage/TopPage.test.tsx
- src/stories/TopPage.stories.tsx
- Added test to TopPage component 🤖

Feat: New TopPage component

---

src/components/index.ts

Added export of the top-page component
Added export of the top-page component
- https://dd360.atlassian.net/jira/software/projects/PD/boards/82?assignee=6397d027fbf54baf29036449&selectedIssue=PD-1169
- src/components/index.ts

Fix(TopPage): Added export of the top-page component

---

src/components/TopPage/TopPage.tsx

Fix(TopPage): Add sticky top page

---

exports.json
package.json
src/components/TableV2/TableV2.tsx
src/components/TableV2/base/Header.tsx
src/components/TableV2/base/HeaderCell.tsx
src/components/TableV2/base/HeaderRow.tsx
src/components/TableV2/base/TableBody.tsx
src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/TableCellText.tsx
src/components/TableV2/base/TableRow.tsx
src/components/TableV2/base/tableV2.css
src/components/TableV2/index.ts
src/components/Typography/Text.tsx
src/components/index.ts
src/stories/TableV2.stories.tsx

Add TableV2 component
- src/components/TableV2/TableV2.tsx
- src/components/TableV2/base/Header.tsx
- src/components/TableV2/base/HeaderRow.tsx
- src/components/TableV2/base/TableBody.tsx
- src/components/TableV2/base/tableV2.css
- src/stories/TableV2.stories.tsx
- Manually

Feat(TableV2): add tableV2 part 1

---

src/components/Filters/FilterSearch.tsx
src/components/TemplatePage/TemplatePage.test.tsx
src/components/TemplatePage/TemplatePage.tsx
src/components/TopPage/TopPage.test.tsx
src/components/TopPage/TopPage.tsx
src/stories/TemplatePage.stories.tsx
src/stories/TopPage.stories.tsx

TemplatePage component was added
- https://dd360.atlassian.net/jira/software/projects/PD/boards/82?assignee=6397d027fbf54baf29036449&selectedIssue=PD-1172
- src/components/Filters/FilterSearch.tsx
- src/components/TemplatePage/TemplatePage.test.tsx
- src/components/TemplatePage/TemplatePage.tsx
- src/components/TopPage/TopPage.test.tsx
- src/stories/TemplatePage.stories.tsx
- src/stories/TopPage.stories.tsx
- Added test to TemplatePage component 🤖

Feat: TemplatePage component was added

---

src/components/TopPage/TopPage.tsx

Styles were modified in the title of the top page
- not

Fix(TopPage): Styles were modified in the title of the top page

---

src/components/Filters/ArrowSelector.tsx

Adjustment in size of options
- not
- src/components/Filters/ArrowSelector.tsx

Fix(ArrowSelector): Adjustment in size of options

---

src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/TableCellText.tsx
src/components/TableV2/base/tableV2.css

Add counter on the cell
- src/components/TableV2/base/TableCellText.tsx
- src/components/TableV2/base/tableV2.css
- Manually
- All tests passed

Feat: add counter to cell

---

src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/tableV2.css

Feat: add blue cell

---

src/components/TableV2/base/HeaderCell.tsx
src/components/TableV2/base/HeaderRow.tsx
src/components/TableV2/base/TableCell.tsx

Add validation sticky cells
- not
- src/components/TableV2/base/HeaderRow.tsx

Fix(TableV2): add validation sticky cells

---

src/components/Form/Select.tsx

Add style dropdown component select
- not

Fix(Style): Add style dropdown component select

---

src/components/TableV2/TableV2.tsx
src/components/TableV2/base/HeaderCell.tsx
src/components/TableV2/base/HeaderRow.tsx
src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/TableInputCell.tsx
src/components/TableV2/base/TableRow.tsx

- Add input cell and change some styles
- src/components/TableV2/TableV2.tsx
- src/components/TableV2/base/HeaderRow.tsx
- src/components/TableV2/base/TableInputCell.tsx
- Manually

Feat: add input cell

---

src/components/TableV2/TableV2.tsx
src/components/TableV2/base/Accordion.tsx

Add accordion table v2
- not
- src/components/TableV2/TableV2.tsx
- src/components/TableV2/base/Accordion.tsx

Fix(TableV2): Add accordion table v2

---

src/components/TableV2/base/HeaderCell.tsx
src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/tableV2.css
src/stories/TableV2.stories.tsx

Add sticky cell shadow
- src/components/TableV2/base/tableV2.css
- src/stories/TableV2.stories.tsx
- Manually

Feat: add sticky cell shadow

---

src/components/SideBar/SideBarItem.tsx
src/components/Tabs/Tab.tsx
src/components/TopPage/TopPage.tsx

The possibility of adding a tooltip to the Tab component has been added.
- not

Fix(Tabs): The possibility of adding a tooltip to the Tab component has been added.

---

src/components/PageTemplate/PageTemplate.tsx

- Change position footer to absolute
- https://dd360.atlassian.net/browse/PD-1049
- src/components/PageTemplate/PageTemplate.tsx
- Manually

Fix(PageTemplate): position absolute on page template footer

---

exports.json
package.json
src/components/ModalV2/ModalV2.test.tsx
src/components/ModalV2/ModalV2.tsx
src/components/ModalV2/index.ts
src/components/index.ts
src/stories/ModalV2Custom.stories.tsx

New Modal component V2
https://dd360.atlassian.net/browse/PD-1417
- src/components/ModalV2/ModalV2.test.tsx
- src/components/ModalV2/ModalV2.tsx
- src/components/ModalV2/index.ts
- src/stories/ModalV2Custom.stories.tsx
Mannualy

feat: new version modal v2

---

exports.json
package.json
src/components/AsideModalV2/AsideModalV2.test.tsx
src/components/AsideModalV2/AsideModalV2.tsx
src/components/AsideModalV2/index.ts
src/components/index.ts
src/stories/AsideModalV2.stories.tsx

Add new component aside modal v2
https://dd360.atlassian.net/browse/PD-1666
- src/components/AsideModalV2/AsideModalV2.test.tsx
- src/components/AsideModalV2/index.ts
- src/stories/AsideModalV2.stories.tsx

feat: Add new component aside modal v2

---

src/components/AsideModalV2/AsideModalV2.tsx
src/components/Buttons/ShapeButton.tsx

Styles were changed
- not
- src/components/Buttons/ShapeButton.tsx

Fix(AsideModalV2): Styles were changed

---

src/components/Form/SingleSelect.test.tsx
src/components/Form/SingleSelect.tsx
src/stories/SelectV2.stories.tsx
src/stories/SingleSelect.stories.tsx

New SingleSelect component added
- https://dd360.atlassian.net/jira/software/projects/PD/boards/82?assignee=6397d027fbf54baf29036449&selectedIssue=PD-1728
- src/components/Form/SingleSelect.test.tsx
- src/stories/SingleSelect.stories.tsx
- Added test to SingleSelect component 🤖

Feat(SingleSelect): New SingleSelect component added

---

src/components/AsideModalV2/AsideModalV2.tsx
src/components/Buttons/Button.tsx
src/components/Buttons/FilterBarButton.tsx

Modified styles of the AsideModalV2, Button and FilterBarButton components
- not
- src/components/Buttons/Button.tsx
- src/components/Buttons/FilterBarButton.tsx

Fix: Modified styles of the AsideModalV2, Button and FilterBarButton components

---

src/components/Form/SingleSelect.tsx
src/stories/SingleSelect.stories.tsx

Correction styles Single Select component
- not
- src/stories/SingleSelect.stories.tsx
- src/stories/SingleSelect.stories.tsx

Fix(SingleSelect): Correction styles Single Select component

---

exports.json
package.json
src/components/index.ts

The Badge component export was corrected.
-  not
- package.json
- src/components/index.ts
- exports.json

Fix(Badge): Component export was corrected.

---

exports.json
package.json
src/components/Form/MultiSelect.test.tsx
src/components/Form/MultiSelect.tsx
src/components/Form/SingleSelect.tsx
src/components/Form/index.ts
src/stories/MultiSelect.stories.tsx

New MultiSelect component added
- https://dd360.atlassian.net/jira/software/projects/PD/boards/82?assignee=6397d027fbf54baf29036449&selectedIssue=PD-1755
- exports.json
- package.json
- src/components/Form/MultiSelect.test.tsx
- src/components/Form/index.ts
- src/stories/MultiSelect.stories.tsx
- Added test to MultiSelect component 🤖

Feat(MultiSelect): New MultiSelect component added

---

src/components/AsideModalV2/AsideModalV2.tsx
src/components/Badge/Badge.test.tsx
src/components/Badge/Badge.tsx
src/components/Buttons/FilterBarButton.tsx
src/components/Form/MultiSelect.test.tsx
src/components/Form/MultiSelect.tsx
src/components/Form/SingleSelect.tsx
src/stories/FilterBarButton.stories.tsx

Small adjustments were made to several components
- not
- src/components/Badge/Badge.test.tsx
- src/components/Badge/Badge.tsx
- src/components/Buttons/FilterBarButton.tsx
- src/components/Form/MultiSelect.test.tsx
- src/stories/FilterBarButton.stories.tsx

Fix: Small adjustments were made to several components

---

src/components/Form/MultiSelect.tsx
src/components/Form/SingleSelect.test.tsx
src/components/Form/SingleSelect.tsx

Small styles adjustment select components
- not
- src/components/Form/SingleSelect.test.tsx

Fix: Small styles adjustment select components

---

src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/TableRow.tsx
tailwind.config.js

- Add a global color named "surface"
- Add the surface color as a new variant of row and cell on TableV2
- https://dd360.atlassian.net/browse/PD-1701
- tailwind.config.js
- Manually

Feat: add accumulate row variant on table v2

---

src/components/TableV2/base/TableRow.tsx

- Change accumulate variant text color
- https://dd360.atlassian.net/browse/PD-1701
- Manually

Fix: change accumulate variant text color

---

src/components/Badge/Badge.tsx
src/components/Form/MultiSelect.tsx
src/components/Form/SingleSelect.tsx
src/components/TableV2/base/Accordion.tsx
src/components/TableV2/base/TableCell.tsx
src/components/TableV2/base/TableCellText.tsx

Small adjustments were made to single select and multi select components
- not

Fix: Small adjustments were made to single select and multi select components

---

src/components/AsideModalV2/AsideModalV2.tsx
src/components/Form/MultiSelect.tsx
src/components/Form/SingleSelect.tsx
src/components/Radio/Radio.tsx

Style adjustments were made to the aside modal v2, single select, multi select and radio components.
- not
- src/components/Radio/Radio.tsx

Fix: Style adjustments were made to the aside modal v2, single select, multi select and radio components.

---

src/components/Form/SingleSelect.tsx
src/stories/SingleSelect.stories.tsx

Add validation label
- not
- src/stories/SingleSelect.stories.tsx

Fix(SingleSelect): Add validation label

---

src/components/Form/SingleSelect.tsx

Fix(SingleSelect): Update state options

---

src/components/Form/Input/InputFile.tsx

Added the props fileName and isLoading
- not

Fix(InputFile): Added the props fileName and isLoading

---

src/components/Form/SingleSelect.tsx

Different validations were added
- not

Fix(SingleSelect): Different validations were added

---

src/components/Form/Input/InputFile.tsx

Validation input file single was modified
- not

Fix(InputFile): Validation input file single was modified
