src/components/Tabs/Tab.tsx, src/components/Tabs/TabGroup.tsx
The state of the tabs did not change when any of their properties changed dynamically
Closes #46
Closes #45
[CD-830](https://dd360.atlassian.net/browse/CD-830)
all test passed ✅
=> fix: the state of the tabs will change when any of its properties change dynamically

.storybook/preview.js, src/theme/ThemeProvider.tsx, src/theme/shared.ts
The ThemeProvider was updated so that the theme was optional, and thus take the lightTheme from the library by default
No yet
```
.storybook/preview.js
src/theme/ThemeProvider.tsx
src/theme/shared.ts
```
already tested
=> fix: add optional theme, use lightTheme by default

src/components/Modal/Modal.tsx
Positions were added for the correct functioning of the modal since if it was inside a component with a margin, the modal also took that margin
`Before:`
`Now:`
- Not yet
- Mannualy
=> fix(Modal): Position modal

src/theme/ThemeProvider.tsx, tailwind.config.js
🧨 Activating this configuration we can make use of the dark mode classes in our tailwind css classes
No Yet
src/theme/ThemeProvider.tsx
tailwind.config.js
=> fix: enable darkMode in tailwindcss config

src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/stories/Pagination.stories.tsx
Previously, the page component was putting a fixed number of options from which the list of elements was cut despite the fact that the total number of elements was less than that list, with this change what is done is that the list of options of cut are made from the number of totalRows so that it does not create more options than they need and in this way make the user see the maximum number of available elements and no more.
- [LEN-649](https://dd360.atlassian.net/browse/LEN-649)
```
src/components/Pagination/Pagination.test.tsx
src/components/Pagination/Pagination.tsx
src/stories/Pagination.stories.tsx
```
=> Feat: list of pagination options based on the number of total elements

src/components/Tabs/Tabs.test.tsx, src/hooks/useTooltip.ts
In this MR:
- change parameters to optionals on `useTooltip`
- remove unnecesary logs of scroll on `Tabs`
[CD-1028](https://dd360.atlassian.net/browse/CD-1028?atlOrigin=eyJpIjoiMTIxMGY1OWQ5NDc0NDk3ZjhiYTg5YTMxOTc4MTZlMDkiLCJwIjoiaiJ9)
=> fix: add missing optional params on useTooltip

src/components/SideBar/SideBar.tsx
Add a z-index to the sidebar to overlay it
[CD-1049](https://dd360.atlassian.net/browse/CD-1049)
=> fix: add a z-index to the sidebar to overlay it

src/components/BarList/BarList.tsx
A minimum right padding has been added to the values so that they are not so close to the background bar.
[Jira task](https://dd360.atlassian.net/browse/CD-1070?atlOrigin=eyJpIjoiOGI1YzcyNTk4NTViNDMyNWI5MTBmODdlODE1NWE2MjkiLCJwIjoiaiJ9)
=> fixed(BarList): added padding-right in values

src/components/SideBar/SideBar.test.tsx, src/components/SideBar/SideBar.tsx, src/components/SideBar/SideBarHeader.tsx, src/components/SideBar/ToggleSideBar.tsx, src/hooks/useResize.ts, src/stories/SideBar.stories.tsx
- For mobile devices, the sidebar will overlay the content.
- For mobile, the button to hide or show the sidebar will be positioned with the reference of its container element.
[CD-1215](https://dd360.atlassian.net/browse/CD-1215)
- src/components/SideBar/ToggleSideBar.tsx
=> refactor: for mobile devices, the sidebar will overlay the content

src/components/SideBar/SideBarItem.tsx
Add validation in SideBarItem
A validation was added, so that in the event that the sidebar is not expanded, when clicking on an item that has subitems, it allows us to be redirected correctly
- [Sidebar](https://dd360.atlassian.net/jira/software/c/projects/CD/boards/12?modal=detail&selectedIssue=CD-1340&assignee=6397d027fbf54baf29036449)
- Mannualy 
=> fix(Sidebar): Add validation in SideBarItem

src/components/DatePicker/DatePicker.tsx, src/components/Table/table.css
- Force hardware acceleration on the table pseudoelement to fix visual bug on Chrome
- Change date picker text when month is selected to color white
- https://dd360.atlassian.net/browse/CD-1155
- src/components/DatePicker/DatePicker.tsx
- src/components/Table/table.css
- Manually
=> Fix: table line and date picker text color

src/components/Table/table.css
- Force hardware acceleration on the table horizontal line to fix visual bug on Chrome
- https://dd360.atlassian.net/browse/CD-1155
- src/components/Table/table.css
- Manually
=> Fix(Table): table horizontal line

src/components/Form/Input/BaseInput.tsx
In some cases, it happens that the input is positioned after the "label", because it has not set the "position", it was only indicated that the "position" is of type "absolute".
The bug was fixed by adding a left-0 right-0 in the input.
[Jira task](https://dd360.atlassian.net/jira/software/c/projects/CD/boards/12?modal=detail&selectedIssue=CD-1708&assignee=63ea68ce9e626e54cc5ac59f)
- Manually in storybook
- Tested in dd360:
=> fix(Input): bug the absolute position

src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
Added the possibility that the close button is not rendered
Not 
- src/components/Modal/Modal.test.tsx
- Mannualy 
=> Fix: added the possibility that the close button is not rendered

src/components/Form/TextArea.tsx
Add prop in text area
A prop was added to be able to customize the size of the text area
[TextArea](https://dd360.atlassian.net/jira/software/c/projects/CD/boards/12?assignee=6397d027fbf54baf29036449&selectedIssue=CD-2098)
- src/components/Form/TextArea.tsx
=> fix(TextArea): add missing className prop 

src/components/Typography/Text.tsx
Added validation of a negative number in currency type text
not
- src/components/Typography/Text.tsx
=> fix(text): Added validation of a negative number in currency type text

src/hooks/useResize.ts
When working with Next.js, there are some cases in which this hook fails, as the page is being loaded on the server and `window` is undefined.
- useResize.ts
- Manually
=> fix(useResize): Fix cases where window was undefined

src/components/SideBar/SideBar.test.tsx, src/components/SideBar/SideBar.tsx
Add a new prop `renderBottomCmp`, to allow placing custom elements at the bottom of the SideBar.
```
<SideBar
sideBarName="Sidebar"
renderBottomCmp={(isExpand) => <MyComponent isExpand={isExpand}/>}
/>
```
This is a required change in order to complete the following task (see Figma): 
- [AK-61](https://dd360.atlassian.net/browse/AK-61)
- SideBar.tsx
=> feat(SideBar): Allow custom element in the dangerZone

src/components/Modal/Modal.tsx
The iconBtnClose prop was added to be able to customize the close button
not
=> Fix(Modal): The iconBtnClose prop was added

src/components/AutoComplete/AutoComplete.test.tsx, src/components/AutoComplete/AutoComplete.tsx
Added new validations for styles when it is disabled and added blocking onChange if it is disabled
not
- src/components/AutoComplete/AutoComplete.tsx
=> Fix(Autocomplete): New validations added

src/components/Tabs/Tab.tsx, src/components/Tabs/TabGroup.tsx, src/components/Tabs/Tabs.test.tsx
Styles are added when hovering in the tabs
not
- src/components/Tabs/Tabs.test.tsx
=> Fix(Tab-Tabgroup): Styles are added when hovering in the tabs

src/components/Form/TextArea.tsx
add validation padding
Validation was added to the padding depending on the label
not
- src/components/Form/TextArea.tsx
=> Fix(TextArea): Validation was added to the padding depending on the label

src/components/Form/Input/BaseInput.tsx, src/components/Form/Input/CurrencyInput.tsx, src/components/Form/Input/PercentageInput.test.tsx, src/components/Form/Input/PercentageInput.tsx
Add prop to customize the number of decimals on the percentage input
- src/components/Form/Input/PercentageInput.test.tsx
- src/components/Form/Input/PercentageInput.tsx
- Manually
- src/components/Form/Input/PercentageInput.test.tsx
=> Feat: add custom decimals to percentage input

.storybook/themes.js, src/components/AsideModal/AsideModal.tsx, src/components/Modal/Modal.tsx, src/hooks/useModalManager.ts, src/stories/Anchor.stories.tsx
✅ Closes: 77 - 80
- Added validation to close the modal 
- Change the default URL of the Anchor component
- Update DD360 Logo URL
- Update of the call to the handleModalClose function
Issues 77 and 80
- src/stories/Anchor.stories.tsx
- src/hooks/useModalManager.ts
- .storybook/themes.js
- src/components/AsideModal/AsideModal.tsx
- Mannualy with storybook :art: 
=> fix(Modal): added validation to prevent close modal

src/components/Tag/Tag.tsx
The div tag was changed to span, in the Tag component
Fix Initial Render Behavior (Hydration):
Since tags are used in paragraphs many times, a "p" tag cannot contain a "div"
Note: Some JavaScript frameworks and libraries, such as Next.js, can generate hydration errors if the HTML markup generated on the server does not exactly match the markup generated on the client. This might be relevant if you are using server-side rendering (SSR).
not
- src/components/Tag/Tag.tsx
Mannualy with storybook 🎨
=> Fix: html change in tag component

src/components/Phase/Phase.tsx, src/stories/Phase.stories.tsx
Different statuses were added in the quarters variant
not
- src/components/Phase/Phase.tsx
- src/stories/Phase.stories.tsx
* Added test to phase component 🤖
=> Fix(Phase): Different statuses were added in the quarters variant

src/components/Dropdown/Dropdown.tsx, src/stories/Dropdown.stories.tsx
Close dropdown when click outside of component
- Not
- src\components\Dropdown\Dropdown.tsx
- src\stories\Dropdown.stories.tsx
- Mannualy with storybook 🎨
=> fix(Dropdown): close dropdown when click outside

src/components/Typography/Text.tsx
fix(Text): when children value is zero number (not string) and variant is currency, the value shows "00"
- Not yet
- src\components\Typography\Text.tsx
- Mannualy with storybook 🎨
=> fix(Text): when children value is zero number (not string) and variant is currency, the value shows "00"

src/components/DateTimePicker/Calendar.tsx, src/components/DateTimePicker/Clock.tsx, src/components/DateTimePicker/DateTimePicker.test.tsx, src/components/DateTimePicker/DateTimePicker.tsx, src/components/DateTimePicker/DateTimePickerWithPortal.tsx, src/components/DateTimePicker/index.ts, src/components/index.ts, src/stories/DateTimePicker.stories.tsx
A new component to select **date** and **time**, can be selected via a dropdown menu or written in an **input tag**
[New component to select date and time](https://dd360.atlassian.net/browse/BK-29)
- src/components/DateTimePicker/Calendar.tsx
- src/components/DateTimePicker/Clock.tsx
- src/components/DateTimePicker/DateTimePicker.test.tsx
- src/components/DateTimePicker/DateTimePicker.tsx
- src/components/DateTimePicker/DateTimePickerWithPortal.tsx
- src/components/DateTimePicker/index.ts
- src/components/index.ts
- src/stories/DateTimePicker.stories.tsx
Mannualy with storybook 🎨
Added test to phase component 🤖
=> Feat: new component DateTimePicker

src/components/Pagination/Pagination.tsx
Display the total items text correctly when the total items are less than the slice size
- https://dd360.atlassian.net/browse/PD-502
- src/components/Pagination/Pagination.tsx
- Manually
=> Fix(Pagination): display total items correctly

src/components/Form/Input/BaseInput.tsx, src/components/Form/Input/MonthInput.tsx, src/components/Form/Input/WrapperInput.tsx
the possibility to customize isCell input has been added
not
- src/components/Form/Input/WrapperInput.tsx
=> Fix(Input): the possibility to customize isCell input has been added

src/components/SideBar/SideBarItem.tsx
tooltip added in titles when text is too long
- not
=> Fix(Sidebar): tooltip added in titles when text is too long

src/components/Form/Input/CurrencyInput.tsx
Disable allow negative number when min prop is zero or more
none
- Manually
=> Fix(CurrencyInput): do not allow negative numbers when min value is zero

src/components/Form/Input/BaseInput.tsx, src/components/Form/Input/MonthInput.tsx
The reason is to be able to limit the minimum and maximum date of date type inputs.
- not
=> Fix(Input): Added minDate and maxDate props in the input component

src/components/AsideModal/AsideModal.tsx
the reason for this change is to have the container of the close button sticky, it is above the other elements.
- not
- src/components/AsideModal/AsideModal.tsx
=> Fix(AsideModal): Add zIndex container close button

src/components/Form/Input/MonthInput.tsx
A higher zindex was added since in some cases it was below other components.
- not
=> Fix(MonthInput): Add zIndex date picker

src/components/SideBar/SideBarItem.tsx
Validation was changed when displaying tooltip
- not
=> Fix(Sidebar): Validation was changed when displaying tooltip

src/components/FileViewer/FileViewer.tsx, src/components/Table/table.css
- Prevent table lines from disappearing when zooming in the browser
- https://dd360.atlassian.net/browse/PD-1032
- src/components/FileViewer/FileViewer.tsx
- src/components/Table/table.css
- Manually
=> Fix(Table): prevent table lines from disappearing when zooming in the browser

src/components/Pagination/Pagination.tsx, src/stories/Pagination.stories.tsx
The width size was changed because when selecting the pagination with a 3-digit value it was cut off.
https://dd360.atlassian.net/browse/PD-1227
- src/components/Pagination/Pagination.tsx
- src/stories/Pagination.stories.tsx
=> fix(Pagination): changed to a width auto

src/components/PageTemplate/PageTemplate.tsx
Change width filter bar search
- not
- src/components/PageTemplate/PageTemplate.tsx
=> Fix(PageTemplate): Change width filter bar search

src/components/Form/Select.tsx
Added prop className to the dropdown of the select component
- not
=> Fix(Select): added prop className to the dropdown of the select component

src/components/TableV2/base/TableInputCell.tsx
Added isError and isBlue props in InputCell
- not
- src/components/TableV2/base/TableInputCell.tsx
=> Fix(TableV2): Add styles props isBlue and isError in InputCell

src/components/TableV2/base/TableCell.tsx, src/components/TableV2/base/TableIndexCell.tsx, src/components/TableV2/base/TableRow.tsx
- Display a pencil icon when Cell component has onEdit prop on hover
- https://dd360.atlassian.net/browse/PD-1158
- src/components/TableV2/base/TableIndexCell.tsx
- Manually
=> Fix: display pencil icon on index cell

src/components/TableV2/base/TableCell.tsx, src/components/TableV2/base/TableRow.tsx
- Rename variant 'header' to 'highlight' on table row and cell row
- Change text size and hover color
none
- Manually
=> Fix: table variant row color

src/components/TableV2/base/TableCellText.tsx
- Display the negative sign in the right position in the currency cell
none
- src/components/TableV2/base/TableCellText.tsx
- Manually
=> Fix: negative number on currency cell

src/components/SideBar/SideBar.tsx, src/components/SideBar/SideBarItem.tsx, src/components/Tabs/Tab.tsx, src/components/Tooltip/Tooltip.tsx
Added the possibility to add tooltip to the sidebar subitem and modified the opacity of the tooltip component.
- not
- src/components/Tooltip/Tooltip.tsx
=> Fix(Sidebar-Tooltip): Added the possibility to add tooltip to the sidebar subitem and modified the opacity of the tooltip component

src/components/TableV2/base/HeaderCell.tsx, src/components/TableV2/base/TableCell.tsx, src/components/TableV2/base/tableV2.css, src/stories/TableV2.stories.tsx
add shadow on the left of the columns
No
- src/components/TableV2/base/tableV2.css
- src/stories/TableV2.stories.tsx
=> feat: add shadow on the left of the columns

src/components/TableV2/base/TableInputCell.tsx
Validation styles disabled was added
- not
- src/components/TableV2/base/TableInputCell.tsx
=> Fix(TableInputCell): Validation styles disabled was added

src/components/PageTemplate/PageTemplate.tsx, src/components/TopPage/TopPage.tsx
- Add hiddenTopPage prop to hide top page
- Add z-index on footer
- https://dd360.atlassian.net/browse/PD-1049
- src/components/PageTemplate/PageTemplate.tsx
- Manually
=> Fix(PageTemplate): add z-index on footer and hide toppage boolean

src/components/AsideModalV2/AsideModalV2.tsx
Modified the way props are extended in the tabs buttons of the AsideModalV2 component
- not
=> Fix: Modified the way props are extended in the tabs buttons of the AsideModalV2 component

exports.json, package.json, src/components/Form/File/FileImageItem.test.tsx, src/components/Form/File/FileImageItem.tsx, src/components/Form/File/FileItem.test.tsx, src/components/Form/File/FileItem.tsx, src/components/Form/File/FileItemButton.test.tsx, src/components/Form/File/FileItemButton.tsx, src/components/Form/File/FileItemDropdown.test.tsx, src/components/Form/File/FileItemDropdown.tsx, src/components/Form/File/FileList.test.tsx, src/components/Form/File/FileList.tsx, src/components/Form/File/index.ts, src/components/Form/Input/InputFile.test.tsx, src/components/Form/Input/InputFile.tsx, src/components/Form/index.ts, src/stories/FileItem.stories.tsx, src/stories/FileItemImage.stories.tsx, src/stories/FileList.stories.tsx, src/stories/InputFile.stories.tsx
- Add FileList, FileItem and FileItemImage
- Redesign of InputFile
- https://dd360.atlassian.net/browse/PD-1708
- exports.json
- package.json
- src/components/Form/File/FileImageItem.test.tsx
- src/components/Form/File/FileImageItem.tsx
- src/components/Form/File/FileItem.test.tsx
- src/components/Form/File/FileItem.tsx
- src/components/Form/File/FileItemButton.test.tsx
- src/components/Form/File/FileItemButton.tsx
- src/components/Form/File/FileItemDropdown.test.tsx
- src/components/Form/File/FileItemDropdown.tsx
- src/components/Form/File/FileList.test.tsx
- src/components/Form/File/FileList.tsx
- src/components/Form/File/index.ts
- src/components/Form/Input/InputFile.test.tsx
- src/components/Form/index.ts
- src/stories/FileItem.stories.tsx
- …
=> Feat: add file list components and redisign of input file

exports.json, package.json, src/components/Filters/DropdownRange.test.tsx, src/components/Filters/DropdownRangeSlider.test.tsx, src/components/Filters/FilterRange.test.tsx, src/components/Filters/FilterRange.tsx, src/components/Filters/FilterRangeSlider.test.tsx, src/components/Filters/FilterRangeSlider.tsx, src/components/Form/ComboSelect.test.tsx, src/components/Form/ComboSelect.tsx, src/components/Form/MultiSelect.tsx, src/components/Form/index.ts, src/stories/ComboSelect.stories.tsx, src/stories/FilterRangeSlider.stories.tsx
- Add ComboSelect component
- Implement component in Multiselect, FilterRangeSlider and FilterRange
- Update layout of FilterRangeSlider and FilterRange
- https://dd360.atlassian.net/browse/PD-1715
- exports.json
- package.json
- src/components/Filters/DropdownRange.test.tsx
- src/components/Filters/DropdownRangeSlider.test.tsx
- src/components/Filters/FilterRange.test.tsx
- src/components/Filters/FilterRange.tsx
- src/components/Filters/FilterRangeSlider.test.tsx
- src/components/Filters/FilterRangeSlider.tsx
- src/components/Form/ComboSelect.test.tsx
- src/components/Form/ComboSelect.tsx
- src/components/Form/index.ts
- src/stories/ComboSelect.stories.tsx
- src/stories/FilterRangeSlider.stories.tsx
- Manually
- All test passed
- …
=> Feat: add combo select component

src/components/Form/SingleSelect.tsx
Validation added to single select component
- not
=> Fix(SingleSelect): Validation added to single select component
